# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-26 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentSubHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.CharField(max_length=256)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubHall',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_hall', to='halls.Hall')),
            ],
        ),
        migrations.CreateModel(
            name='SubHallConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('connected', models.BooleanField(default=False)),
                ('sub_hallA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_hallA', to='halls.SubHall')),
                ('sub_hallB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_hallB', to='halls.SubHall')),
            ],
        ),
        migrations.CreateModel(
            name='SubHallTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=256, unique=True)),
                ('parent_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halls.SubHall')),
            ],
        ),
        migrations.AddField(
            model_name='contentsubhall',
            name='sub_hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halls.SubHall'),
        ),
        migrations.AddField(
            model_name='category',
            name='sub_hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halls.SubHall'),
        ),
    ]
